# Generated by Django 4.2.1 on 2023-05-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualData',
            fields=[
                ('API_WELL_NUMBER', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Oil', models.IntegerField()),
                ('Gas', models.IntegerField()),
                ('Brine', models.IntegerField()),
            ],
        ),
    ]
