# Generated by Django 4.2.1 on 2023-05-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annualdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welldata',
            options={'managed': False},
        ),
    ]
