# Generated by Django 4.2.1 on 2023-05-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welldata',
            name='brine',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='welldata',
            name='gas',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='welldata',
            name='oil',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
