# Generated by Django 4.2.1 on 2023-06-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annualdata', '0002_alter_welldata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welldata',
            options={'managed': False},
        ),
    ]
