# Generated by Django 4.2.1 on 2023-05-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_well_number', models.CharField(max_length=50)),
                ('oil_production', models.IntegerField()),
                ('gas_production', models.IntegerField()),
                ('brine_production', models.IntegerField()),
            ],
        ),
    ]
