# Generated by Django 4.2.1 on 2023-06-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_well_number', models.CharField(max_length=50)),
                ('oil', models.FloatField()),
                ('gas', models.FloatField()),
                ('brine', models.FloatField()),
            ],
            options={
                'db_table': 'annualdata_welldata',
                'managed': False,
            },
        ),
    ]
