# Generated by Django 4.2.1 on 2023-06-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_welldata_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WellData',
        ),
    ]
