# Generated by Django 4.2.1 on 2023-06-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_delete_welldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_well_number', models.CharField(max_length=50)),
                ('oil', models.FloatField()),
                ('gas', models.FloatField()),
                ('brine', models.FloatField()),
            ],
        ),
    ]
