# Generated by Django 4.2.1 on 2023-05-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualData',
            fields=[
                ('well_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('oil', models.IntegerField()),
                ('gas', models.IntegerField()),
                ('brine', models.IntegerField()),
            ],
        ),
    ]
